package RandomGen;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Iterator;
import java.util.Scanner;
import java.util.Vector;

public class FileManager {

	/**
	 * @param args
	 */
	public String input(){
		System.out.println("Enter file name:");
		Scanner in = new Scanner(System.in);
		return in.nextLine();
	}
	public void showFiles(String dirf){
		File dir = new File(dirf);
		String[] children = dir.list();
		if (children == null) {
		    // Either dir does not exist or is not a directory
		} else {
		    for (int i=0; i<children.length; i++) {
		        // Get filename of file or directory
		        System.out.println( children[i]+" ");
		    }
		}
		
	
	}
	public String fileName(){
		String dirName="src/"; 
		String fileName = dirName+input();
		
		File file = new File(fileName);
		while(file.exists()){
			System.out.println(fileName+"File exists!!");
			System.out.println(dirName);
			showFiles(dirName);
			fileName = input();
			file = new File(fileName);
		}
		
		return fileName;
	}
	public BufferedWriter fileWrite() throws Exception{
		
			 String fileName=fileName();
			  FileWriter file = new FileWriter(fileName);
			  BufferedWriter out = new BufferedWriter(file);
			  out.write("This is Changpil\n");
			  out.write("This is generated by FileManager\n");
			 
		return out;	
	}
	
	public boolean writeRandomValue(int line, int col, int max) throws Exception {
		
			BufferedWriter bw = fileWrite();
			RnadomGenerator r = new RnadomGenerator ();
			bw.write("<start>\n");
		
			for(int j=0;j<line;j++){
				Vector<Integer> v= r.generator(col, max); 
	
			
				for(Iterator<Integer> i=v.iterator() ;i.hasNext();){
					bw.write(Integer.toString(i.next())+" ");
				}
				bw.write("\n");	
			}
			bw.write("</start>\n");
			bw.close();
			return true;
	}
	
	public static void main(String[] args) {
		FileManager fm = new FileManager();
		try{
			//fm.writeRandomValue(100,100, Integer.MAX_VALUE);
			fm.writeRandomValue(10,10, 100);
		}catch(Exception e){
			System.err.println(e.getMessage());
		}
		
	}

}
